routes/admin.php
<?php

use App\Models\Backend\Resource;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ResourceController;
use App\Http\Controllers\Backend\AssigmentController;
use App\Http\Controllers\Backend\DashboardController;


Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

Route::resource('users',UserController::class)->except('show');

Route::resource('categories',CategoryController::class)->except('show');

Route::resource('resources',ResourceController::class)->except(['show', 'edit']);
Route::get('/resources/{resource}/categories/{category}', [ResourceController::class, 'edit'])->name('resources.edit');

Route::resource('assigments',AssigmentController::class)->except('show');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;



Route::get('/', HomeController::class)->name('home');

app/Models/Backend/Category.php
<?php

namespace App\Models\Backend;

use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];

    // To date format for created_at field    
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y');
    }

    //  Relation Many to Many (Categories - Resources Tables)
    public function resources()
    {
        return $this->hasMany(Resource::class);
    }

    

}

app/Models/Backend/Resource.php
<?php

namespace App\Models\Backend;

use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Resource extends Model
{
    use HasFactory;
    protected $guarded = [];

    // To date format for created_at field
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y');
    }

     // To date format for asigned_at field    
     public function getAsignedAtAttribute($value)
     {
         return Carbon::parse($value)->format('d/m/Y');
     }

    // Relation many to one inverse (Recourses - Categories Tables)
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    // Relation Many to One ( User - Resources Tables )
    public function user()
    {
        return $this->belongsTo(User::class);
    }


   
}

app/Http/Controllers/Backend/AssigmentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Backend\Resource;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\AssigmentStoreRequest;
use App\Models\Backend\Assigment;
use Carbon\Carbon;
use PhpParser\Node\Expr\Assign;

class AssigmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userResources = User::with('resources')->orderBy('created_at')->get();

        return view('backend.operation.assigments.index', compact('userResources') );

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user      = new User();
        $users     = User::where('id','!=',1)->orderBy('created_at', 'DESC')->get();
        $resources = Resource::where('user_id', NULL)->orderBy('created_at', 'DESC')->get();

        return view('backend.operation.assigments.create', compact( 'user', 'users', 'resources' ) );
    }

   
    public function store(AssigmentStoreRequest $request)
    {
       if ($request->resourcesArray) {
            $resourcesIds = array_unique($request->resourcesArray);                 
            foreach ($resourcesIds as $id) {
                $resource = Resource::findOrFail($id);                
                $resource->update([
                                    'user_id' => $request->user_id,
                                    'note'    => $request->note,
                                    'asigned_at' =>  Carbon::now()
                                 ]);
            }
       }

       return redirect()->route('assigments.index')->with([
           'type' => 'success',
           'msg' => ' En la creación de la Asigación.',
       ]);
    }

   

    
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php


namespace App\Http\Controllers\Backend;


use Illuminate\Http\Request;
use App\Models\Backend\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\CategoryStoreRequest;
use App\Http\Requests\Backend\CategoryUpdateRequest;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all()->sortByDesc('created_at');
        return view('backend.category.index', compact('categories'));
    }

   
    public function create()
    {
        $category = new Category();
       
        return view('backend.category.create', compact('category'));
        
    }

    public function store(CategoryStoreRequest $request)
    {
        $valuesToSave = $request->validated(); 

        Category::create($valuesToSave);

        return redirect()->route('categories.index')->with([
            'type' => 'success',
            'msg' => ' En la Creación de la Nueva Categoría.',
        ]);
    }
   
    public function edit(Category $category)
    {
        return view('backend.category.edit', compact('category') );
    }

   
    public function update(Category $category, CategoryUpdateRequest $request)
    {
        $valuesToSave = $request->validated(); 

        $category->update($valuesToSave);

        return redirect()->route('categories.index')->with([
            'type' => 'success',
            'msg' => ' En la Edición de la Categoría.',
        ]);

    }

   
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('categories.index')->with([
            'type' => 'success',
            'msg' => ' En la Eliminación de la Categoría.',
        ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php



namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Backend\Category;
use App\Http\Controllers\Controller;
use App\Models\Backend\Resource;

class DashboardController extends Controller
{
  
    public function index()
    {
        $usersTotal      = User::where('id','!=',1)->count();
        $categoriesTotal = Category::all()->count();
        $resourcesTotal  = Resource::all()->count();
        
        return view('backend.dashboard', compact( 'usersTotal', 'categoriesTotal', 'resourcesTotal' ) );
    }
}

app/Http/Controllers/Backend/ResourceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Backend\Category;
use App\Models\Backend\Resource;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\ResourceStoreRequest;
use App\Http\Requests\Backend\ResourceUpdateRequest;

class ResourceController extends Controller
{
    public function index()
    {
        $CategoryResources = Category::with('resources')->orderBy('created_at')->get();

        return view('backend.resource.index', compact('CategoryResources'));
        
    }

   
    public function create()
    {
        $users = User::where('id','!=',1)->orderBy('created_at', 'DESC')->get();
        $categories = Category::all()->sortByDesc('name');
        $resource = new Resource();
       
        return view( 'backend.resource.create', compact( 'resource', 'categories', 'users' ) );
        
    }

    public function store(ResourceStoreRequest $request)
    {
        $valuesToSave = $request->validated(); 

        Resource::create($valuesToSave);

        return redirect()->route('resources.index')->with([
            'type' => 'success',
            'msg' => ' En la Creación de la Nuevo Recurso.',
        ]);
    }
   
    public function edit(Resource $resource,  Category $category)
    {
        

        $categories = Category::all()->sortByDesc('name');
        $users = User::where('id','!=',1)->orderBy('created_at', 'DESC')->get();

        
        return view('backend.resource.edit', compact( 'resource','category','categories', 'users' ) );
    }

   
    public function update(Resource $resource, ResourceUpdateRequest $request)
    {
        $valuesToSave = $request->validated(); 

        $resource->update($valuesToSave);

        return redirect()->route('resources.index')->with([
            'type' => 'success',
            'msg' => ' En la Edición del Recurso.',
        ]);

    }

   
    public function destroy(Resource $resource)
    {
        $resource->delete();
        return redirect()->route('recursos.index')->with([
            'type' => 'success',
            'msg' => ' En la Eliminación del Recurso.',
        ]);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\UserStoreRequest;
use App\Http\Requests\Backend\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
   
    public function index()
    {
        $users = User::where('id','!=',1)->orderBy('created_at', 'DESC')->get();
       // dd($users);
        return view('backend.user.index', compact('users'));
    }

   
    public function create()
    {
        $user = new User();
       
        return view('backend.user.create', compact('user'));
        
    }

    public function store(UserStoreRequest $request)
    {
        $valuesToSave = $request->validated();        //dd($valuesToSave);

        User::create($valuesToSave);

        return redirect()->route('users.index')->with([
            'type' => 'success',
            'msg' => 'En la Creación del Nuevo Usuario',
        ]);
    }
   
    public function edit(User $user)
    {
        return view('backend.user.edit', compact('user') );
    }

   
    public function update(User $user, UserUpdateRequest $request)
    {
        $valuesToSave = $request->validated(); 

        $user->update($valuesToSave);

        return redirect()->route('users.index')->with([
            'type' => 'success',
            'msg' => 'En la Edición del Usuario',
        ]);

    }

   
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index')->with([
            'type' => 'success',
            'msg' => 'En la Eliminación del Usuario',
        ]);
    }
}

resources/views/backend/category/create.blade.php
@extends('theme.layouts.backend')
@section('titlePage', 'Crear Nueva Categoría')
@section('sectionTitle', 'Creación de Categoría')
@section('btnHeading')
    <a href="{{ route('categories.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-arrow-left fa-sm text-white-50"></i>
        <span class="ml-1">Regresar a la Lista</span>

    </a>
@endsection

@section('content')
    @include('backend.category.form', $category)
@endsection

resources/views/backend/category/edit.blade.php
@extends('theme.layouts.backend')
@section('titlePage', 'Editar Categría')
@section('sectionTitle', 'Modificar Categoría')
@section('btnHeading')
    <a href="{{ route('categories.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-arrow-left fa-sm text-white-50"></i>
        <span class="ml-1">Regresar a la Lista</span>

    </a>
@endsection

@section('content')
    @include('backend.category.form', $category)
@endsection

resources/views/backend/category/form.blade.php
<div class="card w-75 mx-auto mt-5">
    <div class="card-body">

        @if ($category->exists)
            <form method="POST"  action="{{ route('categories.update', $category) }}" >
                @method('PUT')
        @else
            <form method="POST" action="{{ route('categories.store') }}" >
        @endif
        
        @csrf
         
            <div class="row">

                <div class="mb-4 col-6">
                    <label for="name" class="form-label @error('name') text-danger @enderror requerido">Nombre de la Categoría:</label>
                    <input type="text" 
                        class="form-control @error('name') is-invalid @enderror" 
                        id="name" 
                        name="name"
                        value="{{ old('name', $category->name) }}">
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror

                </div>
                <div class="mb-4 col-6">
                    <label for="description" class="form-label @error('description') text-danger @enderror">Descripción:</label>
                    <input type="text" 
                        name="description" 
                        class="form-control @error('description') is-invalid @enderror" 
                        id="description"
                        value="{{ old('description', $category->description) }}">
                    @error('description')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
           


            <button type="submit" class="btn btn-primary float-right ml-2">{{ __('Save') }}</button>
            <a href="{{ route('categories.index') }}" class="btn btn-danger float-right ">{{ __('Cancel') }}</a>
      </form>

    </div>
</div>

resources/views/backend/category/index.blade.php
@extends('theme.layouts.backend')
@push('css')
{{-- <link href="http://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet"> --}}
<link href="{{ asset('backend/css/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">
@endpush
@section('titlePage','Listado de Categorias')
@section('sectionTitle','Listado de Categorias')
@section('btnHeading')
    <a href="{{ route('categories.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
         <i class="fas fa-folder-plus fa-sm text-white-50"></i>
         <span class="ml-1">Nueva Categoria</span>        
    </a>    
    
@endsection

@section('content')


 <!-- DataTales Example -->
 <div class="card shadow mb-4">
    {{-- <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div> --}}
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Fecha de Creación</th>
                        <th>Acciones</th>
                        
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Fecha de Creación</th>
                        <th>Acciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ( $categories as $category )
                        <tr>
                            
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->description }}</td>                            
                            <td>{{ $category->created_at }}</td>                            
                            <td>
                               
                                <a href="{{ route('categories.edit', $category) }}" class="btn  text-success" data-toggle="tooltip" data-placement="top" title="{{ __('Edit') }}">
                                    <i class="fas fa-edit"></i>
                                </a>
                               
                                <form action="{{ route('categories.destroy', $category)}}" method="post" style="display:inline;">
                                    @method('DELETE')
                                    @csrf
                                    <button data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ __('Delete') }}"
                                            class="btn text-danger"><i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>

                                
                            </td>
                        
                        </tr>
                    @endforeach
                   
                    
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection

@push('js')

<script src="{{ asset('backend/js/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('backend/js/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
<script src="{{ asset('backend/js/datatables-demo.js') }}"></script>

@endpush