routes/admin.php
<?php

use App\Models\Backend\Resource;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ResourceController;
use App\Http\Controllers\Backend\AssigmentController;
use App\Http\Controllers\Backend\DashboardController;


Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

Route::resource('users',UserController::class)->except('show');

Route::resource('categories',CategoryController::class)->except('show');

Route::resource('resources',ResourceController::class)->except(['show', 'edit']);
Route::get('/resources/{resource}/categories/{category}', [ResourceController::class, 'edit'])->name('resources.edit');

Route::resource('assigments',AssigmentController::class)->except('show');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;



Route::get('/', HomeController::class)->name('home');

app/Http/Controllers/Backend/AssigmentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Backend\Resource;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\AssigmentStoreRequest;
use App\Models\Backend\Assigment;
use Carbon\Carbon;
use PhpParser\Node\Expr\Assign;

class AssigmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userResources = User::with('resources')->orderBy('created_at')->get();

        return view('backend.operation.assigments.index', compact('userResources') );

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user      = new User();
        $users     = User::where('id','!=',1)->orderBy('created_at', 'DESC')->get();
        $resources = Resource::where('user_id', NULL)->orderBy('created_at', 'DESC')->get();

        return view('backend.operation.assigments.create', compact( 'user', 'users', 'resources' ) );
    }

   
    public function store(AssigmentStoreRequest $request)
    {
       if ($request->resourcesArray) {
            $resourcesIds = array_unique($request->resourcesArray);                 
            foreach ($resourcesIds as $id) {
                $resource = Resource::findOrFail($id);                
                $resource->update([
                                    'user_id' => $request->user_id,
                                    'note'    => $request->note,
                                    'asigned_at' =>  Carbon::now()
                                 ]);
            }
       }

       return redirect()->route('assigments.index')->with([
           'type' => 'success',
           'msg' => ' En la creación de la Asigación.',
       ]);
    }

   

    
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/operation/assigments/create.blade.php
@extends('theme.layouts.backend')
@push('css')
    <link href="{{ asset('backend/css/select2/select2.min.css') }}" rel="stylesheet">
@endpush
@section('titlePage', 'Asignación de Recursos')
@section('sectionTitle', 'Asignar Recurso')
@section('btnHeading')
    <a href="{{ route('assigments.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-arrow-left fa-sm text-white-50"></i>
        <span class="ml-1">Regresar a la Lista</span>      
    </a>        
@endsection
@section('content')


    <div class="card w-75 mx-auto mt-5">
        <div class="card-body">


            <form method="POST" action="{{ route('assigments.store') }}">

                @csrf
                <div class="row mb-5">

                    <div class=" col-6">
                        <label for="users"
                            class="form-label @error('user_id') text-danger @enderror requerido">
                            Usuario:
                        </label>

                        <select class="form-select form-control users-list" name="user_id"
                            aria-label="Default select example" id="users">

                            <option selected="true" disabled="disabled">Seleccione un Usuario</option>

                            @foreach ($users as $user)

                                @if (old('user_id') == $user->id)
                                    <option value="{{ old('user_id') }}" selected="true">
                                        {{ $user->name }} {{ $user->last_name }}
                                    </option>                                      
                                @else                                 
                                    <option value="{{ $user->id }}">{{ $user->name }} {{ $user->last_name }}</option>
                                
                                @endif
                            @endforeach

                            
                        </select>

                        @error('user_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                        
                    </div>

                    <div class=" col-6">
                        <label for="resource"
                            class="form-label @error('resourcesArray') text-danger @enderror requerido">
                            Recurso(s) para asignar:
                        </label>

                        <select class="form-select form-control resources-list" name="resourcesArray[]" 
                                id="resource" multiple="multiple">

                                {{-- @if (old('user_id') == $user->id)
                                    <option value="{{ old('user_id') }}" selected="true">
                                        {{ $user->name }} {{ $user->last_name }}
                                    </option>                                      
                                @else                                 
                                    <option value="{{ $user->id }}">{{ $user->name }} {{ $user->last_name }}</option>
                                
                                @endif --}}


                            @foreach ($resources as $resource)
                                <option {{ collect( old( 'resourcesArray', $user->resources ) )->contains($resource->id) ? 
                                                    'selected' : '' }} 
                                    value="{{ $resource->id }}">
                                        {{ $resource->name }}
                                </option>

                            @endforeach

                            {{-- @foreach ($tags as $tag)
                            <option {{ collect(old('tags', $post->tags->pluck('id')) )->contains($tag->id) ? 'selected' : '' }} value="{{ $tag->id }}">
                                    {{ $tag->name }}
                            </option>
                        @endforeach --}}
                            
                        </select>
                        @error('resourcesArray')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    
                </div>

                <div class="row mb-5">

                    <div class="col-12">
                        <label for="nota" class="form-label @error('note') text-danger @enderror">Nota:</label>
                        <textarea class="form-control" name="note" id="nota" rows="3">{{ old('note') }}</textarea>
                        @error('note')
                            <div class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </div>
                        @enderror
                    </div>
                   
                </div>

                <button type="submit" class="btn btn-primary float-right ml-2">{{ __('Save') }}</button>
                <a href="{{ route('resources.index') }}" class="btn btn-danger float-right ">{{ __('Cancel') }}</a>
            </form>
        </div>
    </div>



@endsection

@push('js')

    <script src="{{ asset('backend/js/select2/select2.min.js') }}"></script>
    <script>
        $(document).ready(function() {

            $('.users-list').select2();
            
            $('.resources-list').select2({
                placeholder: "Selecione uno o varios recursos",
            });

        });
    </script>

@endpush

resources/views/backend/operation/assigments/index.blade.php
@extends('theme.layouts.backend')
@push('css')
{{-- <link href="http://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet"> --}}
<link href="{{ asset('backend/css/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">
@endpush
@section('titlePage','Recursos Asignados')
@section('sectionTitle','Listado de Recursos Asignados')
@section('btnHeading')
    <a href="{{ route('assigments.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
         <i class="fas fa-boxes fa-sm text-white-50"></i>
         <span class="ml-1">Nueva Asignación</span>        
    </a>        
@endsection

@section('content')


 <!-- DataTales Example -->
 <div class="card shadow mb-4">
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Recurso</th>
                        <th>Fecha de Asignación</th>
                        <th>Acciones</th>
                        
                    </tr>
                </thead>
                <tfoot>
                    <tr>                        
                        <th>Usuario</th>
                        <th>Recurso</th>
                        <th>Fecha de Asignación</th>
                        <th>Acciones</th>
                    </tr>
                </tfoot>
                <tbody>
                    
                    @foreach ( $userResources as $user )

                      @foreach ( $user->resources as $resource )
                        <tr>                            
                            
                            <td>{{ $user->name }} {{ $user->last_name }}</td>
                            <td>{{ $resource->name}}</td>    
                            <td>{{ $resource->asigned_at }}</td>                            
                            <td>                            
                                <a href="{{ route('resources.edit', [$resource, $user]) }}" class="btn  text-success" data-toggle="tooltip" data-placement="top" title="{{ __('Edit') }}">
                                    <i class="fas fa-edit"></i>
                                </a>                            
                                <form action="{{ route('resources.destroy', $resource)}}" method="post" style="display:inline;">
                                    @method('DELETE')
                                    @csrf
                                    <button data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ __('Delete') }}"
                                            class="btn text-danger"><i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>                                
                            </td>                    
                        </tr>
                      @endforeach
                       
                    @endforeach
                   
                   
                    
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection

@push('js')

<script src="{{ asset('backend/js/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('backend/js/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
<script src="{{ asset('backend/js/datatables-demo.js') }}"></script>

@endpush